name: pic-share
services:
  dev:
    build:
      context: .
      dockerfile: dockerfile
      target: builder
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
